language: node_js
node_js:
  - "12.18.3"

git:
  depth: 0
  quite: true

install: npm ci

jobs:
  include:
    - stage: "build & test"
      name: "build application"
      script: npm run build
    - name: "run test"
      script: npm run test